In [2]:
import os
from pathlib import Path

current_directory = Path.cwd()
if current_directory.name == "MT":
    # This means that the notebook is run from the main anomalib directory.
    root_directory = current_directory.parent
elif current_directory.name == "anomalib":
    # This means that the notebook is run from the main anomalib directory.
    root_directory = current_directory

os.chdir(root_directory)
root_directory

PosixPath('/home/wueesmat/MT/anomalib')

In [3]:
import numpy as np

# Import the required modules
from lightning.pytorch import Trainer, seed_everything
from anomalib.data import MVTec
from anomalib.data.image.mvtec import MVTec_contaminated
from anomalib.models import Padim, Patchcore, Stfpm, Draem, EfficientAd
from anomalib.engine import Engine
from anomalib import TaskType



Could not find wandb. To use this feature, ensure that you have wandb installed.
Could not find openvino. To use this feature, ensure that you have openvino installed.
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer.


In [11]:
for idx_category, category in enumerate(category_arr):
    print(results_arr[0,:,idx_category])
    

[0.]


In [ ]:
np.median(results_arr[0,:,:],axis=1)

In [ ]:
np.mean(results_arr[1,:,:],axis=1)

In [ ]:
np.mean(results_arr[2,:,:],axis=1)

In [ ]:
# Save results_arr to a file
np.save("results_arr.npy", results_arr)

In [ ]:
results_arr

In [ ]:
save_folder = "./results/EfficientAD/" #"./results/Padim/"
name = "EfficientAD_20240327.npy" #"Padim_20240327.npy"
file_path = os.path.join(save_folder, name)
np.save(file_path, results_arr)



In [12]:
save_folder = "./results/Padim/"#"./results/Stfpm/" # 
name = "Padim_20240328.npy"#"Stfpm_20240328.npy" # 
file_path = os.path.join(save_folder, name)
file_path

run_arr = np.array([1]) #np.array([1, 2, 3]) #np.array([42])#np.arange(3)+1
cont_ratio_arr = np.array([0.0])#, 0.1]) #np.array([0.0, 0.05, 0.1]) #, 0.15
category_arr = np.array(["carpet"])#, "grid"])#np.array(["carpet", "grid", "leather", "tile", "wood", "bottle", "cable", "capsule", "hazelnut", "metal_nut", "pill", "screw", "toothbrush", "transistor", "zipper"])#np.array(["carpet", "grid"]) #
results_arr = np.empty([run_arr.shape[0], cont_ratio_arr.shape[0], category_arr.shape[0]])

for idx_run, run in enumerate(run_arr):
    for idx_cont_ratio, cont_ratio in enumerate(cont_ratio_arr):
        for idx_category, category in enumerate(category_arr):

            #seed_everything(run, workers=True)
            datamodule = MVTec_contaminated(category=category, cont_ratio=cont_ratio, run=run)
            model = Padim(backbone="resnet18", n_features=100, layers=["layer1", "layer2", "layer3"])
            #model = EfficientAd()
            #model = Stfpm()
            engine = Engine(task=TaskType.CLASSIFICATION, image_metrics=["AUROC", "AUPR", "F1Score"], max_epochs=10, devices=1)

            # Train the model
            engine.fit(datamodule=datamodule, model=model)

            # load best model from checkpoint before evaluating
            test_results = engine.test(
                model=model,
                datamodule=datamodule,
                ckpt_path=engine.trainer.checkpoint_callback.best_model_path,
                verbose=False
            )
            test_results
            results_arr[idx_run, idx_cont_ratio, idx_category] = test_results[0]["image_AUROC"]
            
            print(run)
            print(cont_ratio)
            print(category)

# Save results_arr to the specified folder
np.save(file_path, results_arr)

/home/wueesmat/anaconda3/envs/anomalib_env/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:191: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/wueesmat/anaconda3/envs/anomalib_env/lib/pytho ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
/home/wueesmat/anaconda3/envs/anomalib_env/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
F1Score class exists for backwards compatibility. It will be removed in v1.1. Please us

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [5]:
save_folder = "./results/Patchcore/"#"./results/Stfpm/" # 
name = "Patchcore_all_categories_cont_max_0.15_runs_10_20240331.npy" #"Patchcore_cont_max_0.15_20240328.npy" # "Patchcore_20240328.npy"# 
file_path = os.path.join(save_folder, name)
file_path

# Load the saved array
loaded_array = np.load(file_path)

In [7]:
loaded_array.shape

(1, 1, 1)

In [8]:
loaded_array

array([[[1.]]])

In [13]:
np.mean(loaded_array, axis=0)

array([[0.99464285, 0.99567101, 1.        , 0.98953167, 0.98513938,
        1.        , 0.98705274, 0.97379056, 0.99999995, 0.99834718,
        0.94312601, 0.98265584, 0.99833325, 0.9988889 , 0.99480517],
       [0.99571431, 0.99220777, 1.        , 0.98884294, 0.97275546,
        1.        , 0.98132725, 0.97428044, 1.        , 0.99090911,
        0.93952537, 0.98211381, 0.99749994, 1.        , 0.98685063],
       [0.99696426, 0.98701301, 0.99974489, 0.98980716, 0.97213626,
        1.        , 0.97397528, 0.97232088, 0.99999998, 0.98413225,
        0.93101473, 0.9783198 , 0.99750001, 0.9988889 , 0.98279219],
       [0.99642859, 0.98874459, 0.99987245, 0.98966942, 0.97027867,
        1.        , 0.95810019, 0.96962645, 1.        , 0.97669425,
        0.92986908, 0.97313201, 0.99750001, 0.99555557, 0.97897726]])

In [17]:
for i in range(0,15):
    print(np.mean(loaded_array, axis=0)[:,i])

[0.99464285 0.99571431 0.99696426 0.99642859]
[0.99567101 0.99220777 0.98701301 0.98874459]
[1.         1.         0.99974489 0.99987245]
[0.98953167 0.98884294 0.98980716 0.98966942]
[0.98513938 0.97275546 0.97213626 0.97027867]
[1. 1. 1. 1.]
[0.98705274 0.98132725 0.97397528 0.95810019]
[0.97379056 0.97428044 0.97232088 0.96962645]
[0.99999995 1.         0.99999998 1.        ]
[0.99834718 0.99090911 0.98413225 0.97669425]
[0.94312601 0.93952537 0.93101473 0.92986908]
[0.98265584 0.98211381 0.9783198  0.97313201]
[0.99833325 0.99749994 0.99750001 0.99750001]
[0.9988889  1.         0.9988889  0.99555557]
[0.99480517 0.98685063 0.98279219 0.97897726]


In [31]:
for i in range(0,15):
    perf_loss = np.mean(loaded_array, axis=0)[0,i]-np.mean(loaded_array, axis=0)[3,i]
    print(perf_loss)
perf_loss_arr = np.mean(loaded_array, axis=0)[0,:]-np.mean(loaded_array, axis=0)[3,:]
perf_std_arr = np.std(loaded_array, axis=0)[0,:]-np.std(loaded_array, axis=0)[3,:]

-0.0017857313156127708
0.006926417350769043
0.00012755393981933594
-0.00013774633407592773
0.014860713481902987
0.0
0.02895255088806148
0.0041641116142272505
-4.768371586472142e-08
0.021652925014495783
0.013256931304931663
0.009523820877075151
0.0008332371711731179
0.0033333301544189453
0.01582790613174434


In [32]:
perf_std_arr

array([-1.14375489e-03, -6.41286591e-03, -2.55107880e-04,  8.74962362e-04,
       -1.62052271e-03,  0.00000000e+00, -6.30504374e-03, -3.60000384e-03,
        5.84003864e-08, -9.79959802e-03, -2.01926975e-03, -1.31701674e-03,
       -1.29210416e-03, -6.66666031e-03, -7.54060668e-04])

In [30]:
np.sort(perf_std_arr)

array([-9.79959802e-03, -6.66666031e-03, -6.41286591e-03, -6.30504374e-03,
       -3.60000384e-03, -2.01926975e-03, -1.62052271e-03, -1.31701674e-03,
       -1.29210416e-03, -1.14375489e-03, -7.54060668e-04, -2.55107880e-04,
        0.00000000e+00,  5.84003864e-08,  8.74962362e-04])

In [24]:
perf_loss_arr

array([-1.78573132e-03,  6.92641735e-03,  1.27553940e-04, -1.37746334e-04,
        1.48607135e-02,  0.00000000e+00,  2.89525509e-02,  4.16411161e-03,
       -4.76837159e-08,  2.16529250e-02,  1.32569313e-02,  9.52382088e-03,
        8.33237171e-04,  3.33333015e-03,  1.58279061e-02])

In [25]:
np.sort(perf_loss_arr)

array([-1.78573132e-03, -1.37746334e-04, -4.76837159e-08,  0.00000000e+00,
        1.27553940e-04,  8.33237171e-04,  3.33333015e-03,  4.16411161e-03,
        6.92641735e-03,  9.52382088e-03,  1.32569313e-02,  1.48607135e-02,
        1.58279061e-02,  2.16529250e-02,  2.89525509e-02])

In [ ]:
# cable, metal nut, transistor, 

In [16]:
for i in range(0,15):
    print(np.std(loaded_array, axis=0)[:,i])

[0.00556156 0.00647299 0.00563562 0.00670531]
[0.00474219 0.00793521 0.01161592 0.01115505]
[0.         0.         0.00031244 0.00025511]
[0.01002199 0.01022813 0.00928498 0.00914703]
[0.01362229 0.01457416 0.01253778 0.01524281]
[0. 0. 0. 0.]
[0.00455152 0.0066656  0.01163314 0.01085657]
[0.00357914 0.00446649 0.0042673  0.00717914]
[5.84003864e-08 0.00000000e+00 4.76837158e-08 0.00000000e+00]
[0.0018107  0.007682   0.00868987 0.0116103 ]
[0.00894942 0.00833491 0.00802049 0.01096868]
[0.00596959 0.00397383 0.00518833 0.00728661]
[0.00204122 0.0033333  0.00204123 0.00333332]
[0.0022222  0.         0.0022222  0.00888886]
[0.00303055 0.00346851 0.0045382  0.00378461]


In [4]:
loaded_array

array([[[0.99999994, 1.        , 1.        , 0.99586773, 1.        ,
         1.        , 0.99121672, 0.9748928 , 0.99999988, 0.99504131,
         0.92839605, 0.97328687, 0.99583328, 1.        , 0.99756491],
        [1.        , 1.        , 1.        , 0.99517894, 1.00000012,
         1.        , 0.98503572, 0.96876913, 1.        , 0.97851235,
         0.92348611, 0.98180419, 0.99166667, 1.        , 0.98985386],
        [1.        , 1.        , 1.        , 0.99449027, 0.99690413,
         1.        , 0.98113203, 0.97305572, 1.        , 0.98016536,
         0.91693938, 0.98335272, 0.9958334 , 1.        , 0.98457789],
        [1.        , 1.        , 1.        , 0.99586773, 1.00000012,
         1.        , 0.96844506, 0.97366816, 1.        , 0.96115708,
         0.90916532, 0.96980256, 0.99166667, 1.        , 0.98295456]],

       [[1.        , 1.        , 1.        , 0.97451794, 0.97213626,
         1.        , 0.98893952, 0.97428048, 1.        , 1.00000012,
         0.94885433, 0.98722

In [21]:
loaded_array

array([[[0.99121672, 1.        , 0.99999988],
        [0.98503572, 1.        , 1.        ],
        [0.98113203, 1.        , 1.        ],
        [0.96844506, 1.        , 1.        ]],

       [[0.98893952, 1.        , 1.        ],
        [0.97592711, 1.        , 1.        ],
        [0.97462595, 1.        , 1.        ],
        [0.94925183, 1.        , 1.        ]],

       [[0.98893952, 1.        , 1.        ],
        [0.97364992, 1.        , 1.        ],
        [0.9739753 , 1.        , 1.        ],
        [0.9450227 , 1.        , 1.        ]],

       [[0.98796356, 0.99444449, 0.99999988],
        [0.99219263, 1.        , 1.        ],
        [0.98731291, 0.99444449, 1.        ],
        [0.97299933, 0.97777784, 1.        ]],

       [[0.97820437, 1.        , 1.        ],
        [0.97983086, 1.        , 1.        ],
        [0.9528302 , 1.        , 0.99999988],
        [0.95478201, 1.        , 1.        ]]])

In [ ]:
# Initialize the datamodule, model and engine
#datamodule = MVTec(category="carpet")
#datamodule = MVTec_contaminated(category="carpet")
seed_everything(2, workers=True)
category = "carpet"
cont_ratio=0.1#0.05#0.1#0 #0.05
datamodule = MVTec_contaminated(category=category, cont_ratio=cont_ratio, run=2)
#model = Padim(backbone="wide_resnet50_2", n_features=550, layers=["layer1", "layer2", "layer3"]) #EfficientAd() #Draem() #Patchcore() #Stfpm()
model = Padim(backbone="resnet18", n_features=100, layers=["layer1", "layer2", "layer3"])
engine = Engine(task=TaskType.CLASSIFICATION, image_metrics=["AUROC", "AUPR", "F1Score"])


In [ ]:
# Train the model
engine.fit(datamodule=datamodule, model=model)

In [ ]:
# load best model from checkpoint before evaluating
test_results = engine.test(
    model=model,
    datamodule=datamodule,
    ckpt_path=engine.trainer.checkpoint_callback.best_model_path,
    verbose=False
)
test_results

In [ ]:
test_results[0]

In [ ]:
[{'image_AUROC': 0.8588435053825378, 'image_F1Score': 0.8253968358039856}]

In [ ]:
test_results[0]["image_AUROC"]

In [ ]:
from lightning.pytorch import Trainer, seed_everything
import numpy as np

seed_everything(1, workers=True)


#model = Padim(backbone="wide_resnet50_2", n_features=550, layers=["layer1", "layer2", "layer3"]) #EfficientAd() #Draem() #Patchcore() #
model = Padim(backbone="resnet18", n_features=100, layers=["layer1", "layer2", "layer3"])
#model = Padim()
engine = Engine(task=TaskType.CLASSIFICATION)

category_arr = np.array(["carpet", "grid", "leather", "tile", "wood", "bottle", "cable", "capsule", "hazelnut", "metal_nut", "pill", "screw", "toothbrush", "transistor", "zipper"])


In [ ]:
image_AUROC_ls

In [ ]:
np.round(image_AUROC_ls,3)

In [ ]:
np.mean(image_AUROC_ls)

In [ ]:
np.round(image_AUROC_ls,3)

In [ ]:
np.mean(image_AUROC_ls)

In [ ]:
image_AUROC_ls = []
image_F1Score_ls = []
category_arr_short = category_arr#[0:2]
for idx, category in enumerate(category_arr_short):
    print(category)

    # Initialize the datamodule, model and engine
    seed_everything(42, workers=True)
    datamodule = MVTec(category=category)
    #model = Padim(backbone="resnet18", n_features=100, layers=["layer1", "layer2", "layer3"])
    #model = Padim(backbone="wide_resnet50_2", n_features=550, layers=["layer1", "layer2", "layer3"]) #EfficientAd() #Draem() #Patchcore() 
    model = Patchcore(backbone="wide_resnet50_2") 
    engine = Engine(task=TaskType.CLASSIFICATION)
    
    # Train the model
    engine.fit(datamodule=datamodule, model=model)

    # load best model from checkpoint before evaluating
    test_results = engine.test(
        model=model,
        datamodule=datamodule,
        ckpt_path=engine.trainer.checkpoint_callback.best_model_path,
        verbose=False
    )
    
    image_F1Score_ls.append(test_results[0]['image_F1Score'])
    image_AUROC_ls.append(test_results[0]['image_AUROC'])


In [ ]:
image_F1Score_ls

In [ ]:
image_F1Score_ls

In [ ]:
np.mean(image_F1Score_ls)

In [ ]:
results_ls

In [ ]:
results_ls[0]